create table if not exists profile.users
(
    id           bigint generated by default as identity primary key,
    auth_id      uuid        not null unique,
    display_name varchar(32) not null,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
)