package io.uliss.exception.utils

enum class ErrorCode {
    SECURITY_ERROR,
    AUTHORIZATION_CODE_ERROR,
    INVALID_REFRESH_TOKEN_ERROR,
    NOT_FOUND_ERROR,
    INTERNAL_ERROR,
    BAD_REQUEST_ERROR,
    VALIDATION_ERROR,
    UNKNOWN_ERROR,
    EMAIL_FORMAT_ERROR,
    PASSWORD_FORMAT_ERROR
}