apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/auth/deployment.yaml
  - k8s/auth/service.yaml
  - k8s/user/deployment.yaml
  - k8s/user/service.yaml
  - k8s/note/deployment.yaml
  - k8s/note/service.yaml
  - k8s/web/deployment.yaml
  - k8s/web/service.yaml
  - k8s/ingress.yaml

secretGenerator:
  - name: uliss-secret
    envs:
      - .env
    options:
      disableNameSuffixHash: true

patches:
  - path: k8s/patch-k8s-secret.yaml