spring:
  config:
    import:
      - classpath:database.yml
      - classpath:exception.yml
  application:
    name: auth
  threads:
    virtual:
      enabled: true
  flyway:
    schemas: auth
    default-schema: auth
