import Markdown from 'react-markdown'
import rehypeSanitize from 'rehype-sanitize'
import remarkGfm from 'remark-gfm'
import './markdown-content.css'

interface MarkdownContentProps {
    content: string
}

function isExternalLink(href: string | undefined): boolean {
    return href != null && /^https?:\/\//i.test(href)
}

/** Safe CommonMark/GFM renderer for content generated by the assistant. */
export function MarkdownContent({content}: MarkdownContentProps) {
    return (
        <div className="markdown-content">
            <Markdown
                skipHtml
                disallowedElements={['img']}
                remarkPlugins={[remarkGfm]}
                rehypePlugins={[rehypeSanitize]}
                components={{
                    a: ({node: _node, href, children, ...props}) => {
                        const external = isExternalLink(href)
                        return <a {...props} href={href}
                                  target={external ? '_blank' : undefined}
                                  rel={external ? 'noopener noreferrer' : undefined}>{children}</a>
                    },
                }}
            >
                {content}
            </Markdown>
        </div>
    )
}
