import Markdown from 'react-markdown'
import rehypeSanitize, {defaultSchema} from 'rehype-sanitize'
import remarkGfm from 'remark-gfm'
import './markdown-content.css'

interface MarkdownContentProps {
    content: string
    pending?: boolean
}

interface MarkdownNode {
    type: string
    children?: MarkdownNode[]
    data?: {
        hName?: string
        hProperties?: Record<string, unknown>
    }
}

function findLastInlineBlock(node: MarkdownNode): MarkdownNode | null {
    if (node.type === 'paragraph' || node.type === 'heading' || node.type === 'tableCell') return node
    for (const child of [...(node.children ?? [])].reverse()) {
        const target = findLastInlineBlock(child)
        if (target) return target
    }
    return null
}

function appendStreamingCaret() {
    return (tree: MarkdownNode) => {
        const target = findLastInlineBlock(tree) ?? tree
        target.children ??= []
        target.children.push({
            type: 'streamingCaret',
            data: {
                hName: 'span',
                hProperties: {className: ['bubble-cursor'], ariaHidden: true},
            },
        })
    }
}

const markdownSanitizeSchema = {
    ...defaultSchema,
    attributes: {
        ...defaultSchema.attributes,
        span: [
            ...(defaultSchema.attributes?.span ?? []),
            ['className', 'bubble-cursor'],
            'ariaHidden',
        ],
    },
}

function isExternalLink(href: string | undefined): boolean {
    return href != null && /^https?:\/\//i.test(href)
}

/** Safe CommonMark/GFM renderer for content generated by the assistant. */
export function MarkdownContent({content, pending = false}: MarkdownContentProps) {
    return (
        <div className="markdown-content">
            <Markdown
                skipHtml
                disallowedElements={['img']}
                remarkPlugins={pending ? [remarkGfm, appendStreamingCaret] : [remarkGfm]}
                rehypePlugins={[[rehypeSanitize, markdownSanitizeSchema]]}
                components={{
                    a: ({node: _node, href, children, ...props}) => {
                        const external = isExternalLink(href)
                        return <a {...props} href={href}
                                  target={external ? '_blank' : undefined}
                                  rel={external ? 'noopener noreferrer' : undefined}>{children}</a>
                    },
                }}
            >
                {content}
            </Markdown>
        </div>
    )
}
