apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: uliss/user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: uliss-secret
      restartPolicy: Always
      