spring:
  config:
    import:
      - classpath:database.yml
      - classpath:exception.yml
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  flyway:
    schemas: profile
    default-schema: profile

