server:
  port: ${USER_SERVER_PORT:8080}

spring:
  application:
    name: user-service
  config:
    # noinspection SpringBootApplicationYaml
    import:
      - classpath:database.yml
      - classpath:exception.yml
      - classpath:security.yml
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${POSTGRES_URL}?currentSchema=profile
  flyway:
    schemas: profile
    default-schema: profile
security:
  oauth2:
    client:
      # noinspection SpringBootApplicationYaml
      redirect-uri: ${USER_SERVICE_URL}/oauth2/callback

